### ISSUE TITLE
[BUG] TypeError: this.window.scrollTo is not a function

### ISSUE THREAD

**Issue by syahirudean** [ng-web-apis/common#47]
# 🐞 Bug report

### Description

Tried using ng-web-apis / common to fix global object issues when using Angular Universal (SSR), but after injecting WINDOW into the component that I'm using, I still faced the error `ERROR TypeError: this.window.scrollTo is not a function` 

### Expected behavior

I'm expecting that the error will not prompt and able to use global objects on Angular universal
.
### Versions

-   OS: macOS]
-   Browser Chrome
-   Angular v13

### Additional context

content in component:
`export class MainComponent {
  constructor(
    @Inject(WINDOW) readonly window: Window,
    @Inject(LOCAL_STORAGE) readonly localStorage: Storage,
    private modal_service: ModalService
  ) {}
  onActivate() {
    this.window.scrollTo(0, 0);
  }`

Error: 

`ERROR TypeError: this.window.scrollTo is not a function
    at MainComponent.onActivate (/Users/syahiruddin/RVI/app/dist/functions/server/main.js:621:21)
    at MainComponent_Template_router_outlet_activate_3_listener (/Users/syahiruddin/RVI/app/dist/functions/server/main.js:644:159)
    at executeListenerWithErrorHandling (/Users/syahiruddin/RVI/app/dist/functions/server/main.js:161451:16)
    at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (/Users/syahiruddin/RVI/app/dist/functions/server/main.js:161489:22)
    at ConsumerObserver.__webpack_modules__.3317.ConsumerObserver.next (/Users/syahiruddin/RVI/app/dist/functions/server/main.js:86077:33)
    at SafeSubscriber.__webpack_modules__.3317.Subscriber._next (/Users/syahiruddin/RVI/app/dist/functions/server/main.js:86044:26)
    at SafeSubscriber.__webpack_modules__.3317.Subscriber.next (/Users/syahiruddin/RVI/app/dist/functions/server/main.js:86015:18)
    at /Users/syahiruddin/RVI/app/dist/functions/server/main.js:85840:34
    at Object.errorContext (/Users/syahiruddin/RVI/app/dist/functions/server/main.js:94538:9)
    at EventEmitter_.__webpack_modules__.3125.Subject.next (/Users/syahiruddin/RVI/app/dist/functions/server/main.js:85832:24)`

**Comment by waterplea** [comment]
Yes, default `window` under Angular's `DOCUMENT` token is lacking. You need to add mocks for server side:
https://github.com/ng-web-apis/universal
