### ISSUE TITLE
[BUG] - requestAnimationFrame is not a function

### ISSUE THREAD

**Issue by KhaledGabr** [ng-web-apis/common#65]
# 🐞 Bug report

### Description

I get this error when running: npm run dev:ssr

**ERROR TypeError: requestAnimationFrame is not a function**
    at subscriber (./node_modules/@ng-web-apis/common/fesm2015/ng-web-apis-common.js:25:18)
    at _trySubscribe (./node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at cb (./node_modules/rxjs/dist/cjs/internal/Observable.js:35:31)
    at errorContext (./node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at subscribe (./node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
    at init (./node_modules/rxjs/dist/cjs/internal/operators/share.js:83:47)
    at call (./node_modules/rxjs/dist/cjs/internal/util/lift.js:14:28)
    at cb (./node_modules/rxjs/dist/cjs/internal/Observable.js:30:30)
    at errorContext (./node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Observable.Observable.subscribe (./node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)

### Versions
-   OS: [e.g. iOS] Windows 10
-   Browser [e.g. chrome, safari]  Chrome
-   Angular [e.g. 8]  16.0.0-next.7

**Comment by waterplea** [comment]
For the SSR you need to provide mocks, use this dedicated package:
https://github.com/ng-web-apis/universal

**Comment by waterplea** [comment]
> Thanks @waterplea. The issue was on my end indeed as I didn't import UniversalModule correctly for my standalone app. 
> 
> For anyone who face this issue and happens to use standalone components.
> 
> It can be imported as follows:
> const serverConfig: ApplicationConfig = {
>   providers: [provideServerRendering(), importProvidersFrom(UniversalModule)],
> };
> 

Thanks for the code sample, we probably need it in the README.md. If you have time to create a PR, that would be very helpful!

**Comment by MustafaTheEngineer** [comment]
I get `requestAnimationFrame is not a function` error. I followed the docs but mocks doesn't exist in `@ng-web-apis/universal`. When I import `@ng-web-apis/universal/mocks` I get this error: `Missing "./mocks" specifier in "@ng-web-apis/universal" package`. And alos where the UniversalModule come from?
